### ISSUE TITLE
[CallAdmin: Ts3 module] Error on receiving tracker count: HTTP status code 500

### ISSUE THREAD

**Issue by olokos** [Impact123/CallAdmin#34] opened 2019-09-27 12:04 UTC
I'm getting this error when just somebody is on the server, not really sure what is causing this
the same happens for calladmin/ts3/index.php via browser but calladmin/notice.php works fine
I'm using latest sourcemod, I have just compiled all of the plugins I used myself, except for this one as I need to be sure it works great before recompiling it myself.

I'm also running MySQL 8 and PHP 7.3 and yes, everything else is running great. I have updated and fixed each and every failing/outdated plugin so far by hand, here I'm quite confused where to even look for the problem

**Comment by Impact123** [comment] 2019-09-27 12:06
Do you use [the development version](https://github.com/Impact123/CallAdmin/releases)? If not please try if it's fixed by updating to it.

[HTTP code 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) means internal server error. I need to see some logs of your web server.
To trigger the error you can use the url the ts3 module uses in your browser
```
sm_calladmin_ts3_url/onlinecount.php?key=sm_calladmin_ts3_key
```
Where **sm_calladmin_ts3_url** and **sm_calladmin_ts3_key** are replaced by their convar's value respectively.

You can also [add me on steam](https://steamcommunity.com/id/I-Zum-M/) if you want.

**Comment by olokos** [comment] 2019-09-27 12:15
I am using the development version!
But you were right, I have borked the syntax of app.config.php
Now that that's fixed everything should be working, but not really. 
I can see the serveradmin connecting to ts3 via query, but it's not notifying anybody when using !calladmin_test
theres no notification via steam either
Adding you on steam right now!

**Comment by Impact123** [comment] 2019-09-27 12:50
This was caused by a missing bcmath module and fixed by installing it.

**Closed as completed by Impact123** 2019-09-27 12:50 UTC
